### ISSUE TITLE
Review and Update Licensing Information for External Dependencies

### ISSUE THREAD

**Issue by syslaz** [syslaz/ziotic#1]
**Description:**

We have identified that several source files within the Ziotic codebase originate from different projects under various licenses, including GNU and Apache licenses. Currently, our `LICENSE.txt` states the MIT License, which may not accurately reflect the entire codebase’s licensing situation.

**Task List:**
- [ ] Identify all files and directories that originate from external codebases or libraries.
- [ ] Determine their specific licenses (e.g., GNU, Apache, etc.).
- [ ] Update project documentation to clearly reflect these licenses.
- [ ] If necessary, include or reference any required license notices (e.g., `LICENSE-THIRD-PARTY.txt` or inline comments).
- [ ] Ensure that the final licensing documentation is compliant with all third-party requirements.

**Additional Notes:**
- This issue aims to ensure transparency and compliance with all relevant licenses.
- Once resolved, we will have a clear and comprehensive understanding of all licenses applying to our codebase, enabling future contributors and users to understand their obligations and rights.

Please comment on this issue with any known license sources or relevant information. Once the review is complete, we will update the documentation and close the issue.

**Comment by advnau** [comment]
server/src/main/java/com/ziotic/gnu/getopt this package is GPLv2 library version. It looks like its just a shaded version of the library. 
 
Perhaps the best bet to avoid colliding with the MIT license on this would be to use the artifact available at 

```
// https://mvnrepository.com/artifact/gnu.getopt/java-getopt
implementation 'gnu.getopt:java-getopt:1.0.13'
```

**Comment by advnau** [comment]
That library is only used for com.ziotic.jode package and subpackages. Im not sure if this is merely a shaded copy of jode or if there were changes made to the decompiler in order to support rs better. The rest of the game server does not call it. Also this library is GNU LGPL licensed also.

The other 3P library that stands out is the com.ziotic.asm which is a copy of the objectweb asm library which is a BSD license. Its only used by the updater. Once again, im not sure if there were changes made in ziotic but this license is MIT compatible, but I think its preferred to use the copy of central rather than a shaded if there arnt relevant changes.
